---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-fqdn-konsole-is-v1alpha1-networkpolicy
  failurePolicy: Fail
  name: mnetworkpolicy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - fqdn.konsole.is
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networkpolicies
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-fqdn-konsole-is-v1alpha1-networkpolicy
  failurePolicy: Fail
  name: vnetworkpolicy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - fqdn.konsole.is
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networkpolicies
  sideEffects: None
