# This rule is not used by the project fqdn-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over fqdn.konsole.is.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: fqdn-controller
    app.kubernetes.io/managed-by: kustomize
  name: networkpolicy-admin-role
rules:
- apiGroups:
  - fqdn.konsole.is
  resources:
  - networkpolicies
  verbs:
  - '*'
- apiGroups:
  - fqdn.konsole.is
  resources:
  - networkpolicies/status
  verbs:
  - get
