# This rule is not used by the project fqdn-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the fqdn.konsole.is.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: fqdn-controller
    app.kubernetes.io/managed-by: kustomize
  name: networkpolicy-editor-role
rules:
- apiGroups:
  - fqdn.konsole.is
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fqdn.konsole.is
  resources:
  - networkpolicies/status
  verbs:
  - get
