apiVersion: v1
entries:
  fqdn-controller:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2025-07-19T00:33:10.378181688Z"
    description: A Helm chart to distribute the project fqdn-controller
    digest: 38417e86fb3a6fd0f3b3ec4e3ade1c5d47f77eb1711415690aa0f963c5d9ca69
    icon: https://github.com/konsole-is/fqdn-controller/blob/master/dist/chart_icon.png?raw=true
    name: fqdn-controller
    sources:
    - https://github.com/konsole-is/fqdn-controller
    type: application
    urls:
    - https://konsole-is.github.io/fqdn-controller/charts/fqdn-controller-0.0.1.tgz
    version: 0.0.1
generated: "2025-07-19T00:33:10.377501111Z"
