apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "fqdn-controller.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "fqdn-controller.fullname" . }}-serving-cert
  labels:
  {{- include "fqdn-controller.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "fqdn-controller.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-fqdn-konsole-is-v1alpha1-networkpolicy
  failurePolicy: Fail
  name: mnetworkpolicy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - fqdn.konsole.is
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networkpolicies
  sideEffects: None
