apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fqdn-controller.fullname" . }}-networkpolicy-editor-role
  labels:
  {{- include "fqdn-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - fqdn.konsole.is
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fqdn.konsole.is
  resources:
  - networkpolicies/status
  verbs:
  - get
