name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Build and Publish Artifacts
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    env:
      TAG: ${{ github.ref_name }}
      IMG: ghcr.io/${{ github.repository }}:${{ github.ref_name }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: v3.18.4
        id: install

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: make docker-build IMG=${IMG}

      - name: Push Docker image
        run: make docker-push IMG=${IMG}

      - name: Generate Kustomize release manifests
        run: |
          make build-installer IMG=${IMG}
          kustomize build config/crd > crds.yaml
          helm package dist/chart

      - name: Upload release files
        uses: softprops/action-gh-release@v2
        with:
          files: |
            install.yaml
            crds.yaml
            fqdn-controller-${TAG}.tgz

      - name: Set up Git for GitHub Pages
        if: github.event.release.prerelease == false
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"

      - name: Checkout gh-pages branch
        if: github.event.release.prerelease == false
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy Helm chart and update index.yaml
        if: github.event.release.prerelease == false
        run: |
          mkdir -p gh-pages/charts
          cp fqdn-controller-${TAG}.tgz gh-pages/charts/
          cd gh-pages/charts
          helm repo index . --url https://konsole-is.github.io/fqdn-controller/charts

      - name: Push updated Helm repo to gh-pages
        if: github.event.release.prerelease == false
        run: |
          cd gh-pages
          git add charts
          git commit -m "Update Helm repo for ${TAG}" || echo "No changes to commit"
          git push origin gh-pages